### ISSUE TITLE
Feat: Learn + Document How to Setup Recurring Payment Processing

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-payment-processing#1]
Thinking of using **`Stripe`** as their APIs are decent. 🧑‍💻 
(Fly.io are using **`Stripe`** and the interface is seamless!)
Buuuutttt ... from experience, _many_ people have **`PayPal`** accounts  ... 📈 
And then there's Amazon Pay, Apple Pay and Google Play Store ... 🙄 

So let's take a step back and consider our requirements. 💭 

# Requirements

+ [ ] Simplest possible interface for making/collecting payments.
+ [ ] Single payments (e.g. Year-in-advance) first
+ [ ] Recurring payments e.g: Monthly second.
+ [ ] Understand what is required to create a "Merchant Account"?
+ [ ] Document everything in as much detail as possible.
+ [ ] Create a basic `App` that connects to a `Sandbox` API.
+ [ ] Ship the basic app to Fly.io so that we can all test it using dummy credit cards.

# Story

As a person wanting to maximise their personal effectiveness,
I want to pay up-front for the service 
so I know exactly what I'm getting.

# Priority?

I know this might not _look_ like the highest priority when our `MVP` is _far_ from _useful_ at this point.
But as soon as it _is_ useful, we want to have the pricing page on dwyl.com _ready_ and payment collection enabled
because it lends _credibility_ to the product. i.e. if people know they can _pay_ for it, they know it's "real".

**Comment by nelsonic** [comment]
@LuchoTurtle how much have you looked into Payment Processing? 💳 
Does understanding how this all works _appeal_ to you? 💰 
If not, don't worry; it's not everyone's cup-of-tea. 🍵 
But if you're keen, please comment. 💬 🙏

**Comment by LuchoTurtle** [comment]
I've never worked with payment processing before but I guess I'll have a look 👍

**Comment by LuchoTurtle** [comment]
@nelsonic I have a few questions, as this topic seems a bit broad.
- Should I narrow this to an Elixir API? Flutter?
- Should I use [Stripe](https://github.com/beam-community/stripity-stripe)? The issue implies using other gateways...?

**Comment by nelsonic** [comment]
For now we just need generic research that is applicable to _any_ programming language that can make HTTP (REST API) requests. This can be `Python`, `JavaScript` or `Elixir`. 

When we are creating our _example_ we can use `Elixir` or `Rust`. 

As for using **`Stripe`**, yes, for now that is the appropriate gateway/provider.
I've left it open in the OP because if `PayPal` has a _comparable_ UI/UX/API and pricing, we could use that.

**Comment by nelsonic** [comment]
The _reason_ I've left `PayPal`, `ApplePay`, `GoogleWallet` in the OP is simple: Critical Mass.
`PayPal` has **`377 Million`** active people using their App/service!
There's a _very_ good chance that a person wanting to use _our_ app _already_ has a `PayPal` account.
And since they most likely are logged into their `PayPal` on the computer/phone they are using,
then it's just 2 taps to checkout. 🏁 💰 🎉

**Comment by nelsonic** [comment]
Wasteful screenshot:

![mega-screenshot](https://user-images.githubusercontent.com/17494745/209158781-5242b18f-9abb-4c0c-8703-5be7ed9509f7.png)

Constrained (show just the info needed and minimise whitespace) screenshot:
![redirect-to-auth](https://user-images.githubusercontent.com/194400/212059730-91137e3a-9a34-43e1-9cbe-9732511adcbd.png)

This might not seem like such a big deal. But these add up over time.
Don't waste people's bandwidth or time scrolling through unnecessarily large images.

I've hidden the "or email" because it's not relevant to this example.

**Comment by nelsonic** [comment]
![stripity-stripe](https://user-images.githubusercontent.com/194400/212060290-9044031a-4d6a-4127-b049-278c0543297f.png)
