### ISSUE TITLE
Coverage unknown

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/learn-payment-processing#19]
Currently, the `coverage` is showing "unavailable". 

<img width="528" alt="image" src="https://user-images.githubusercontent.com/17494745/213671436-fc8ad565-0317-4eab-9984-1de996a8f4db.png">

Should be fairly simple to fix this, since running `mix tests` yield 100% coverage.

**Comment by nelsonic** [comment]
FYI: the fact that you nudged this on the Codecov site means the badge is _already_ working:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/194400/213680686-fbf75dc6-d2ed-4343-90d2-f0fc0693b436.png">
